### ISSUE TITLE
По поводу вкладки Projects

### ISSUE THREAD

**Issue by CADproject** [CADproject/Editor#10]
Я сделал там первый проект, в котором описал свою текущую задачу.

Оказалось, что это мощная штука, надо будет в ней получше разобраться
и использовать ее в работе.

Там можно вести проекты, к которым можно прикреплять карточки с текущими задачами
и событиями (например pull request, открытие/закрытие issue).

**Comment by MageNuada** [comment]
Я уже было подумал, что можно назначать проекты.) А потом увидел, что это лишь текстовое описание.)

**Comment by AlexeyKalinichenko** [comment]
В проектах есть столбцы, на которые добавляются карточки.
