### ISSUE TITLE
Elements which not in base.

### ISSUE THREAD

**Issue by MageNuada** [CADproject/Editor#13]
В контроллере мы можем создавать элементы без добавления их в базу: а что будет с их отрисовкой? контроллер будет два списка(элементы из базы, и элементы не из базы) совмещать и передавать во вью? И второй список у себя хранить или в ядре?

**Comment by AlexeyKalinichenko** [comment]
Нет, контроллер отправляет их в  ядро, ядро добавляет их в свой буфер всех отображаемых объектов, фильтрует и отправляет на вью.

**Comment by MageNuada** [comment]
"и отправляет на вью." отправляет в контроллер по запросу вью-вызов отрисовки-контроллер-вызов списка объектов для отрисовки.

**Comment by AlexeyKalinichenko** [comment]
Да
