### ISSUE TITLE
Отклики из ядра.

### ISSUE THREAD

**Issue by MageNuada** [CADproject/Editor#17]
Ситуация: мы из контроллера вызываем какую-то функцию ядра. Внутри во время выполнения происходит ошибка/что-то не смогло выполниться(пример, создании линии, но линия не создалась). Далее контроллер на основе возвращаемых данных из этой функции должен будет что-то делать, но по сути данные будут не валидны, потому что в ядре не прошла операция. Соответственно, контроллеру надо как-то знать, что функция выполнилась, имеет ли это смысл?

**Comment by AlexeyKalinichenko** [comment]
Контроллер узнает об этом ещё до отображения, в интерфейсе ядра будут исключения. А после всех действий контроллера, все будет выполняться гарантировано.

**Comment by AlexeyKalinichenko** [comment]
Ты ставишь под сомнение самый массово используемый архитектурный шаблон, который используется уже несколько десятилетий (MVC) ?

**Comment by MageNuada** [comment]
Нет, конечно.)  Я именно ставлю на рассмотрение, есть ли необходимость детализировать общение контроллера и модели.

**Comment by AlexeyKalinichenko** [comment]
В смысле детализировать?

**Comment by MageNuada** [comment]
Было обсуждено на совещании.
