### ISSUE TITLE
Изменение размера изображения

### ISSUE THREAD

**Issue by AlexeyKalinichenko** [CADproject/Editor#26]
При уменьшении/увеличивании окна редактора уменьшается/увеличивается изображение.

**Comment by MageNuada** [comment]
Это не баг, это нормальное поведение.

**Comment by AlexeyKalinichenko** [comment]
Нет, это баг. При изменении вертикального размера окна, размер изображения изменяется (а не должен), а при изменении горизонтального размера окна - остается прежним (это правильно).
