### ISSUE TITLE
Взаимодействие компонентов MVC

### ISSUE THREAD

**Issue by AlexeyKalinichenko** [CADproject/Editor#3]
Предлагаю решить здесь проблему взаимодействия ядра/контроллера/отображения.

Первый вопрос - взаимодействие ядра и отображения.
По идее это односторонняя связь со стороны ядра. Ядро оповещает об изменениях и отправляет данные на отрисовку. Нужно разобраться в протоколе взаимодействия.

**Comment by CADproject** [comment]
Получается что не односторонняя. View тоже должна отправлять.

**Comment by MageNuada** [comment]
Вариант 1. Механизм как мне сейчас видится:
Ядро отправляет события объект добавлен/объект удалён + у контроллера есть возможность запросить свойства объекта (видимый или нет, дата для отрисовки). Такая схема также переносит граф сцены в длл контроллера.
Вариант 2. Ядро на самом деле отправляет тогда только данные для отрисовки. В плане совсем-совсем данные. При этом вызывается раз перерисовка - и всё. Такая схема означает, что вся логика на стороне ядра, менеджер сцены и прочее.

Перечитав текст, скажу: основное различие в стороне нахождения менеджера и определении набора объектов для отрисовки. В случае стороны шарпов - то тогда они должны иметь доступ к классам объектов или представлению этих классов.

**Comment by AlexeyKalinichenko** [comment]
Надо будет на примере ядра для конкретики обсудить
