### ISSUE TITLE
Косметические правки

### ISSUE THREAD

**Issue by AlexeyKalinichenko** [CADproject/Editor#42]
1) Поправить  "1.0.6272.19931" на "1.0.0.0" на верхней панели с названием главного окна;

2) Сделать в главном окне промежутки между кнопками одинаковые;

3) Менеджер слоев. Активная секция в таблице выделяется жирной рамкой, а активная строчка в этой же таблице выделяется синим цветом. Если это  убрать, то будет очень круто.

**Comment by MageNuada** [comment]
1. https://habrahabr.ru/post/119400/ в студии есть автогенерация номера сборки и номера ревизии - она как раз и включена. Помогает точнее отследить, какая версия дебага была при тестировании. Кстати, для этого предлагаю хранить в девелопе бинарные файлы.

**Comment by AlexeyKalinichenko** [comment]
Почитал, это скорее для больших проектов. Не вижу смысла усложнять.

**Comment by AlexeyKalinichenko** [comment]
Тем более у нас сборки не централизованные.
