### ISSUE TITLE
Проблема контейнеров/коллекций при взаимодействии C# и С++

### ISSUE THREAD

**Issue by AlexeyKalinichenko** [CADproject/Editor#5]
При создании и разрушении контура в плюсах используются STL контейнеры. Работа с контурами будет на стороне шарпов, который использует свои коллекции. Собственно вопрос во взаимодействии. Использовать обычные массивы? Или задействовать дотнетовский си++, в котором конвертировать?

**Comment by MageNuada** [comment]
"используются STL контейнеры" - смотря какие контейнеры.
Вопрос, что ты подразумеваешь под работой с контурами?
Передача массива объектов между шарпами-плюсами - возможна передача массива структур.

**Comment by AlexeyKalinichenko** [comment]
хотя контейнеры - это те же объекты...

> Вопрос, что ты подразумеваешь под работой с контурами?

методы контуров на вход принимают контейнеры или возвращают их

**Comment by MageNuada** [comment]
Контейнеры - это объекты класса, нельзя сделать соответствие таких классов между шарпами и плюсами.
Я посмотрю код - значит, в обёртке приходящие данные будут конвертироваться в контейнеры и наоборот. Но точнее смогу сказать позже.

**Comment by AlexeyKalinichenko** [comment]
Да нет, я про то что их можно по указателю void передавать, сделав для них обертку. и шарповские коллекции уже вручную по ним заполнять.

**Comment by AlexeyKalinichenko** [comment]
Есть еще вариант. Vector умеет возвращать указатель на первый элемент его внутреннего массива.

**Comment by MageNuada** [comment]
Напиши пример, пожалуйста, что ты именно хочешь передавать в теории между шарпами и плюсами и чем именно заполнять в шарпах?

**Comment by AlexeyKalinichenko** [comment]
Для создания контура по ребрам (их число при компиляции не известно) нужен массив данных, сам контур из си++, а создаваться будет на си#.

Ну в общем проблема решена.

**Comment by MageNuada** [comment]
Я понял решение. Не нужно оборачивать классы из плюсов. Надо передавать массив IntPtr.
IntPtr[] objects = new IntPtr[5]; к примеру.
В него кладутся указатели объектов. А далее этот массив просто передаётся в плюсы. Передача массива структур в плюсы - старая известная тема.

**Comment by AlexeyKalinichenko** [comment]
Можешь пример кода сделать?

**Comment by MageNuada** [comment]
Да, Запощу через 10 минут в свою ветку изменённый код.
