### ISSUE TITLE
Edges and objects

### ISSUE THREAD

**Issue by MageNuada** [CADproject/Editor#6]
Ты рёбра по IntPtr ведёшь(при отправке в шарповую часть), а объекты по айди: может, имеет смысл всё к одному типу привести?

**Comment by AlexeyKalinichenko** [comment]
По id ведутся объекты, которые записаны в базу. А по IntPtr свободные объекты для построений или временных отображений.

**Comment by AlexeyKalinichenko** [comment]
Id - это идентификатор объекта базы, указатели таких объектов не доступны из контроллера.

**Comment by MageNuada** [comment]
Понял.
