### ISSUE TITLE
Обсуждение взаимодействия View и Controller

### ISSUE THREAD

**Issue by CADproject** [CADproject/Editor#9]
Предлагаю вести обсуждение по этой теме здесь.

**Comment by MageNuada** [comment]
Ок.

Нужны данные для отрисовик элементов в 2д.
Нужны входная функция для контроллера - для операций.

**Comment by AlexeyKalinichenko** [comment]
Да, ядро через контроллер будет возвращать все данные, как бы на отрисовку. Все норм.

UPD: это совсем плохой вариант

**Comment by AlexeyKalinichenko** [comment]
Отправка данных на отрисовку из ядра во вью может происходить двумя способами.

1) Когда вью сам запрашивает информацию у контроллера, чтобы тот запросил её у ядра (то о чем мы говорили)

2) Когда ядро принудительно отправляет данные во вью на отрисовку (собственно модель MVC)

Второй способ мне нравится больше. Т.к вью не нужно задумываться когда спросить данные.
Во вью вообще не должно быть бизнес логики, её задача - отображение.

**Comment by AlexeyKalinichenko** [comment]
Интерфейс контроллера (6 методов):

//вызывается при запуске приложения
`SessionId initSession()`

//вызывается при создании документа, возвращает идентификатор
`DocumentId initDocument(SessionId sessionID)`

//вызывается при выполнении одного из трех событий, движение мыши, правая/левая кнопка мыши
`void eventHendling(mouseEvents action, double coordX = 0, double coordY = 0)`
//если событие "move" - передаются координаты
`enum mouseEvents : byte { leftButton, rightButton, move }`

//вызывается при выполнении операции
`void procOperation(SessionId sessionID, DocumentId docID, OperationId opID, Object[] data)`

//вызывается при закрытии документа
`void finalDocument(SessionId sessionID, DocumentId docID)`

//вызывается при закрытии приложения
`void finalSession(SessionId sessionID)`

**Comment by MageNuada** [comment]
finalDocument
finalSession
Замени, пожалуйста, final на close, потому что это может немного путать.

**Comment by AlexeyKalinichenko** [comment]
Так зачем ты ветку влил, если у тебя были претензии к коду?)
Теперь мне надо будет править master или до следующего реквеста.

**Comment by MageNuada** [comment]
Но без твоих изменений я не мог править свой код, потому что он был зависим от твоего кода.
К сожалению, у нас сейчас задачи сильно переплетаются, так как это самое начало, так что, имхо, не страшно такое.

**Comment by AlexeyKalinichenko** [comment]
Так сделал бы пока совместимым свой код, а потом все в следующий реквест включили бы

**Comment by AlexeyKalinichenko** [comment]
Мы, получается опять от формализма уходим на ручную работу, где все надо разруливать

**Comment by MageNuada** [comment]
Про данные:
+третий вариант - отрисовка по таймеру - каждые Х тиков.
И это всё так, только если отрисовкой занимается VIew. В таком случае я был бы за вызов данных отрисовки по таймеру/из вью, потому что в ином случае(на первый взгляд сейчас) много случаев, когда в коде ядра надо будет ставить самому себе(ядру) уведомление на перерисовку - это может привести к пропущенным моментам каким-либо в отрисовке.

**Comment by AlexeyKalinichenko** [comment]
Ядру не не нужны уведомления, оно итак все знает, тем более этот момент в будущем будет оптимизироваться, а оптимизация и логика во вью - это нонсенс

**Comment by MageNuada** [comment]
Я имею ввиду, что у элемента изменился, например, цвет - ядро должно начать себя перерисовывать? Ещё что-нибудь произошло - снова перерисовка?

**Comment by AlexeyKalinichenko** [comment]
Дим, мы идем по классической модели MVC, где вью выполняет только функцию отображения, а ты хочешь добавить сюда элементы MVVM или MVP. Получится уродливая неработоспособная архитектура, эти схемы уже проверены годами, нет смысла им не доверять и изобретать велосипед.

**Comment by MageNuada** [comment]
Помечаю: данное обсудили в голосовом чате скайпа.
